<x-welcome-banner />
<x-in-the-press />
<x-collection-sale />
<x-best-sellers />
<x-exclusive-bundles />
<x-customer-testimonials />
<x-founder />
<x-blog-posts />
@section('description', $meta_description)
